### ISSUE TITLE
Implement ModelMapper Backend Functionality

### ISSUE THREAD

**Issue by spring-boot-react** [spring-boot-react/full-stack-spring-boot-security-jwt-postgresql-docker-nextjs#9]
ModelMapper is a Java library that helps in mapping objects from one model to another, reducing the need for manual mapping code. It is a highly configurable library that uses conventions to automatically map objects, but can also be configured to provide custom mapping rules.

See: [https://modelmapper.org/getting-started/](https://modelmapper.org/getting-started/)

Note: Bean Configuration and Maven Dependency already exist within the project.

**Comment by darksos34** [comment]
Added modelmapper + DTO
